/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:d2f36390-2ce8-4265-ab8a-9b85f6cee816",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_wKAv899RO",
    "aws_user_pools_web_client_id": "7gfu7m4iv9g9u5uhsu75a1e68o",
    "oauth": {}
};


export default awsmobile;
